[workspace]
resolver = "2"
members = [
    "crates/ferrum-common",
    "crates/ferrum-ids",
    "crates/ferrum-api",
    "crates/ferrum-proto",
    "crates/ferrum-crypto",
    "crates/ferrum-policy",
    "crates/ferrum-compiler",
    "crates/ferrum-wasm-abi",
    "crates/ferrum-wasm-host",
    "crates/ferrum-ebpf",
    "crates/ferrum-ebpf-progs",
    "crates/ferrum-k8smeta",
    "crates/ferrum-admission",
    "crates/ferrum-agent",
    "crates/ferrum-controller",
    "crates/ferrum-export",
    "crates/ferrum-cli",
    "crates/ferrum-testkit",
]

[workspace.package]
version = "0.1.0"
edition = "2021"
license = "GPL-3.0-only"
publish = false
rust-version = "1.75"

[workspace.dependencies]
ferrum-common = { path = "crates/ferrum-common" }
ferrum-ids = { path = "crates/ferrum-ids" }
ferrum-api = { path = "crates/ferrum-api" }
ferrum-proto = { path = "crates/ferrum-proto" }
ferrum-crypto = { path = "crates/ferrum-crypto" }
ferrum-policy = { path = "crates/ferrum-policy" }
ferrum-compiler = { path = "crates/ferrum-compiler" }
ferrum-wasm-abi = { path = "crates/ferrum-wasm-abi" }
ferrum-wasm-host = { path = "crates/ferrum-wasm-host" }
ferrum-ebpf = { path = "crates/ferrum-ebpf" }
ferrum-ebpf-progs = { path = "crates/ferrum-ebpf-progs" }
ferrum-k8smeta = { path = "crates/ferrum-k8smeta" }
ferrum-export = { path = "crates/ferrum-export" }
ferrum-testkit = { path = "crates/ferrum-testkit" }

anyhow = "=1.0.81"
chrono = { version = "=0.4.35", default-features = false, features = ["clock", "serde", "std"] }
clap = { version = "=4.4.18", features = ["derive"] }
serde = { version = "=1.0.197", features = ["derive"] }
serde_json = "=1.0.114"
serde_yaml = "=0.8.26"
thiserror = "=1.0.58"
tracing = "=0.1.40"
