[package]
name = "ferrum-crypto"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true
rust-version.workspace = true

[dependencies]
ed25519-compact.workspace = true
ferrum-common.workspace = true
ferrum-ids.workspace = true
ring = "0.17"
rustls-pemfile.workspace = true
rustls-pki-types.workspace = true
rustls-webpki.workspace = true
sha2.workspace = true

[dev-dependencies]
rcgen = "0.13"
